### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by vedantmgoyal9** [Macleykun/Macleykun#1]
Hi @macleykun,

I'm vedant, maintainer of winget-pkgs-automation (https://github.com/vedantmgoyal2009/winget-pkgs-automation) (reference: https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/1196)

I need a little help from you. If you're available, is there any way I can message you directly? Like on social media like twitter, or gitter?

Thanks in advance.

**Comment by Macleykun** [comment]
> Hi @Macleykun,
> 
> I'm vedant, maintainer of winget-pkgs-automation (https://github.com/vedantmgoyal2009/winget-pkgs-automation) (reference: [vedantmgoyal9/vedantmgoyal2009#1196](https://github.com/vedantmgoyal9/vedantmgoyal2009/issues/1196))
> 
> I need a little help from you. If you're available, is there any way I can message you directly? Like on social media like twitter, or gitter?
> 
> Thanks in advance.

Sure feel free to add me on discord: Macley
Don’t have any other sm’s sadly, but if you don’t want to use discord I can make something temporally

**Comment by Macleykun** [comment]
> I have sent a hello, please check if you did receive. multiple results were appearing in the search, so wanted to confirm i haven't sent it to wrong person. my discord is `vedantmgoyal`. if you haven't received anything, please drop a hi from your account.

Didn’t get a message but send a friend req to ya!
